### ISSUE TITLE
Issue: UserProfile Updating a Record 

### ISSUE THREAD

**Issue by mohammad-omar-01** [MustafaIrshaidd/EnvironmentalMonitoringandReportingPlatform#2]
**When Updating a record for a user, a new user must not be added to the database, you have only to update the current user, and not inserting a new one** 

So Update the put method for the user with his id to update the user found in the database only not creating a new one

**Comment by MustafaIrshaidd** [comment]
Its now updating without creating new user.
Issue is Solved and merged to the development branch
